Only one application object
As Jesse Jiang mentions in a later comment, we forgot to delete theApp
from the console application. We can't compile with this here:

2>c:\...\mfcapp2dll\win32caller\win32caller.cpp(15): error C2371:
'theApp' : redefinition; different basic types
2>          c:\...\mfcapp2dll\mfcindll\mfcindll.h(37) : see declaration
of 'theApp'